### ISSUE TITLE
Question: production examples

### ISSUE THREAD

**Issue by tanis2000** [koding/kite#131]
Hi! I'm evaluating Kite for future projects and I thought it would really help to have a list of production projects that are using Kite. Is it available anywhere?
Cheers!

**Comment by Depado** [comment]
I'd love some of those too. Examples with multiples arguments, more complex data structure than "just" a float64 would be awesome !

**Comment by fatih** [comment]
Hi All,

We have examples under the folder: https://github.com/koding/kite/tree/master/examples

Below is a gif that shows how easy it is. First I call the [`math-kite`](https://github.com/koding/kite/tree/master/examples/math/math-kite) (Right side).  On the left side, I'm using the [`math-cli`](https://github.com/koding/kite/tree/master/examples/math/math-cli) to send manual arguments. First I send the number `4` and then `12`. The `math-kite` is responsible of squaring the number and returning it back to me. 

In the end I'm just calling another kite ([`exp2`](https://github.com/koding/kite/blob/master/examples/exp2/exp2.go)), it's like `math-cli` but instead of manual numbers it's periodically sending random numbers to `math-kite`:

![screen capture on 2015-10-27 at 11-54-10](https://cloud.githubusercontent.com/assets/438920/10753427/94fbc930-7c99-11e5-90f1-ab429e59ff8a.gif)

If you have more questions please let me know!

**Comment by Depado** [comment]
Doing a math operation is simple indeed and that behaviour is well documented. But what if I want to send more complex data to the Kite ? What are the best way ? Should I use `r.Args.Slice()` ? `r.Args.One().Map()` and pass a map to the client ? How can I pass more complex data structures to Kite, like a struct directly that I could unmarshall on receive ? 

I mean there is only one example using `MustFloat64`, with a single argument. 
I like the way `Kontrol` works (registering allows more scalability and with the authentication system it's exactly what I'm looking for). `Kite` needs more documentation...

**Comment by fatih** [comment]
@Depado here is an example of using structs: https://github.com/koding/kite/pull/140

Let me clarify this. You can send as many as arguments. So arguments are sent as an array to the kite. The arguments can be anything, like a number, slice, map, struct, etc.. 

In the PR above I'm sending only one struct, so I'm doing a `r.Args.One()` because it's a handy helper to get only one argument (side note: it's actually a wrapper around ` r.Args.MustSliceOfLength(1)[0]
`) 

After I get the arguments, I'm just doing an Unmarshal. Because I know the request struct, both `math-cli` and `math-kite` is using `math.Request` struct. 

Actually this is how we use it in production at Koding. We have a file of Request and Response structs. We send arguments via single struct. Response can be also a struct if you wish, and in that case it's the same, you have to Unmarshal via the `response`, like `response.Unmarshal()` instead of `response.MustFloat64`)

**Comment by fatih** [comment]
> Kite needs more documentation...

I agree on that. I would be happy if we could document more of the stuff. It's just we have many other things to do and usually docs are always neglected and not prioritized. Right now we have to figure it ourself and I agree it sucks.

**Comment by Depado** [comment]
Any way you could provide a more complex example then ? With a more complex data structure or something like that ?
